{"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/errorDescription"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"s:14Authentication18OAuthProviderErrorO16errorDescriptionSSSgvp","symbolKind":"property","modules":[{"name":"Authentication"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"errorDescription"},"kind":"symbol","variants":[{"paths":["\/documentation\/authentication\/oauthprovidererror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","type":"topic","url":"\/documentation\/authentication","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"role":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OAuthProviderError"}],"abstract":[{"text":"A type that indicates when OAuth operartion encounters an error.","type":"text"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/errorDescription":{"url":"\/documentation\/authentication\/oauthprovidererror\/errordescription","type":"topic","title":"errorDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/errorDescription","kind":"symbol","role":"symbol"}}}