{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failed"},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/authentication\/oauthprovidererror\/failed"]}],"abstract":[{"type":"text","text":"The authorization attempt failed."}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"roleHeading":"Case","modules":[{"name":"Authentication"}],"symbolKind":"case","title":"OAuthProviderError.failed","externalID":"s:14Authentication18OAuthProviderErrorO6failedyA2CmF"},"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/failed":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failed","abstract":[{"type":"text","text":"The authorization attempt failed."}],"role":"symbol","kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/failed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"title":"OAuthProviderError.failed","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"type":"topic","url":"\/documentation\/authentication","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","abstract":[],"title":"Authentication"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OAuthProviderError"}],"navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}],"url":"\/documentation\/authentication\/oauthprovidererror","abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"role":"symbol","title":"OAuthProviderError"}}}