{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The authorization attempt failed."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failed"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/authentication\/oauthprovidererror\/failed"]}],"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"Authentication"}],"title":"OAuthProviderError.failed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"externalID":"s:14Authentication18OAuthProviderErrorO6failedyA2CmF","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/failed":{"role":"symbol","abstract":[{"text":"The authorization attempt failed.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failed","type":"topic","title":"OAuthProviderError.failed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/failed"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","url":"\/documentation\/authentication","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","role":"collection","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OAuthProviderError","kind":"identifier"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","role":"symbol"}}}