{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"general"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/authentication\/oauthprovidererror\/general(message:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/general(message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The authorization attempt failed for an unknown reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"general"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"OAuthProviderError.general(message:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:14Authentication18OAuthProviderErrorO7generalyACSS_tcACmF","modules":[{"name":"Authentication"}]},"hierarchy":{"paths":[["doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication","doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError"]]},"references":{"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError/general(message:)":{"role":"symbol","title":"OAuthProviderError.general(message:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"general"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The authorization attempt failed for an unknown reason."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError\/general(message:)","kind":"symbol","type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/general(message:)"},"doc://com.ibm.iOS-SDK/documentation/Authentication/OAuthProviderError":{"role":"symbol","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthProviderError"}],"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication\/OAuthProviderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}],"url":"\/documentation\/authentication\/oauthprovidererror"},"doc://com.ibm.iOS-SDK/documentation/Authentication":{"role":"collection","title":"Authentication","abstract":[],"identifier":"doc:\/\/com.ibm.iOS-SDK\/documentation\/Authentication","kind":"symbol","type":"topic","url":"\/documentation\/authentication"}}}