{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failureReason","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/helpAnchor","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/recoverySuggestion"]}],"identifier":{"url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"LocalizedError Implementations","modules":[{"name":"Authentication"}],"role":"collectionGroup","roleHeading":"API Collection"},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","url":"\/documentation\/authentication","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","role":"collection","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/helpAnchor":{"abstract":[],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/helpanchor","title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/helpAnchor","type":"topic","role":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OAuthProviderError","kind":"identifier"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","role":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/failureReason":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/failurereason","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"failureReason"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/recoverySuggestion":{"role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/recoverySuggestion","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/recoverysuggestion"}}}