{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations"},"metadata":{"role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"Authentication"}],"roleHeading":"API Collection"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failureReason","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/helpAnchor","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/recoverySuggestion"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"kind":"article","references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/helpAnchor":{"url":"\/documentation\/authentication\/oauthprovidererror\/helpanchor","title":"helpAnchor","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"type":"topic","url":"\/documentation\/authentication","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","abstract":[],"title":"Authentication"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/failureReason":{"url":"\/documentation\/authentication\/oauthprovidererror\/failurereason","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failureReason","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","abstract":[],"title":"failureReason"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/recoverySuggestion":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/recoverySuggestion","abstract":[],"kind":"symbol","title":"recoverySuggestion","url":"\/documentation\/authentication\/oauthprovidererror\/recoverysuggestion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"kind":"symbol","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OAuthProviderError"}],"navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}],"url":"\/documentation\/authentication\/oauthprovidererror","abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"role":"symbol","title":"OAuthProviderError"}}}