{"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"LocalizedError Implementations","roleHeading":"API Collection","modules":[{"name":"Authentication"}],"role":"collectionGroup"},"topicSections":[{"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failureReason","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/helpAnchor","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/recoverySuggestion"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/recoverySuggestion":{"url":"\/documentation\/authentication\/oauthprovidererror\/recoverysuggestion","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/recoverySuggestion","abstract":[],"role":"symbol","title":"recoverySuggestion","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/helpAnchor":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/helpanchor","title":"helpAnchor","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/helpAnchor"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","type":"topic","url":"\/documentation\/authentication","kind":"symbol","role":"collection","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"role":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OAuthProviderError"}],"abstract":[{"text":"A type that indicates when OAuth operartion encounters an error.","type":"text"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/failureReason":{"title":"failureReason","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/failurereason","abstract":[],"role":"symbol","kind":"symbol"}}}