{"topicSections":[{"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failed","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/general(message:)","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/invalidResponse"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/errorDescription"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/Equatable-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/Error-Implementations","doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations"]}],"abstract":[{"text":"A type that indicates when OAuth operartion encounters an error.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OAuthProviderError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","title":"OAuthProviderError","roleHeading":"Enumeration","externalID":"s:14Authentication18OAuthProviderErrorO","modules":[{"name":"Authentication"}],"navigatorTitle":[{"kind":"identifier","text":"OAuthProviderError"}],"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuthProviderError"}]},"hierarchy":{"paths":[["doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","doc:\/\/com.ibm.verify.ios.sdk\/SQ","doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/authentication\/oauthprovidererror"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/errorDescription":{"url":"\/documentation\/authentication\/oauthprovidererror\/errordescription","type":"topic","abstract":[],"title":"errorDescription","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/errorDescription","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.ibm.verify.ios.sdk/s5ErrorP":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication":{"abstract":[],"title":"Authentication","url":"\/documentation\/authentication","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication","role":"collection","kind":"symbol","type":"topic"},"doc://com.ibm.verify.ios.sdk/s8SendableP":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.ibm.verify.ios.sdk/SQ":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/LocalizedError-Implementations":{"type":"topic","url":"\/documentation\/authentication\/oauthprovidererror\/localizederror-implementations","kind":"article","abstract":[],"title":"LocalizedError Implementations","role":"collectionGroup","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/LocalizedError-Implementations"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError":{"abstract":[{"type":"text","text":"A type that indicates when OAuth operartion encounters an error."}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror","title":"OAuthProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"OAuthProviderError","kind":"identifier"}],"navigatorTitle":[{"text":"OAuthProviderError","kind":"identifier"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError","type":"topic","role":"symbol"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/Equatable-Implementations":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article","title":"Equatable Implementations","url":"\/documentation\/authentication\/oauthprovidererror\/equatable-implementations","abstract":[]},"doc://com.ibm.verify.ios.sdk/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/failed":{"role":"symbol","abstract":[{"text":"The authorization attempt failed.","type":"text"}],"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/failed","type":"topic","title":"OAuthProviderError.failed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/failed"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/general(message:)":{"identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/general(message:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"general"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","title":"OAuthProviderError.general(message:)","url":"\/documentation\/authentication\/oauthprovidererror\/general(message:)","abstract":[{"text":"The authorization attempt failed for an unknown reason.","type":"text"}]},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/Error-Implementations":{"abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/Error-Implementations","title":"Error Implementations","role":"collectionGroup","url":"\/documentation\/authentication\/oauthprovidererror\/error-implementations"},"doc://com.ibm.verify.ios.sdk/documentation/Authentication/OAuthProviderError/invalidResponse":{"title":"OAuthProviderError.invalidResponse","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidResponse"}],"abstract":[{"text":"The authorization request received an invalid response.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.ibm.verify.ios.sdk\/documentation\/Authentication\/OAuthProviderError\/invalidResponse","kind":"symbol","url":"\/documentation\/authentication\/oauthprovidererror\/invalidresponse"}}}